# Generated by Django 2.0.7 on 2018-08-01 17:04

import accounts.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('address_name', models.CharField(blank=True, max_length=50, verbose_name='氏名')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=50, null=True, verbose_name='性別')),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Facebook ID')),
                ('line_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='LINE ID')),
                ('is_line_only', models.BooleanField(default=False, verbose_name='LINEのみのユーザー')),
                ('is_verified', models.BooleanField(default=False, verbose_name='認証完了')),
                ('hopes_newsletters', models.BooleanField(default=False, verbose_name='配信希望')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
