# Generated by Django 2.0.6 on 2018-08-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item_in_cart',
        ),
    ]
