# Generated by Django 2.0.6 on 2018-08-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='user',
            name='address_name_kana',
            field=models.CharField(blank=True, max_length=50, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, choices=[('teens', '～10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代～')], max_length=50, null=True, verbose_name='年齢層'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='市区町村'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='番地・建物名'),
        ),
    ]
