# Generated by Django 2.0.7 on 2018-08-01 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'answers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bland',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='ブランド名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ブランド',
                'verbose_name_plural': 'ブランド',
                'db_table': 'blands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='カラー分類名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('code', models.CharField(max_length=50, verbose_name='カラーコード')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カラー分類',
                'verbose_name_plural': 'カラー分類',
                'db_table': 'color_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=50, verbose_name='カラー')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('is_tsa', models.BooleanField(default=True, verbose_name='TSAロック対応')),
                ('fee_intercept', models.IntegerField(verbose_name='料金切片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bland', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Bland', verbose_name='ブランド')),
                ('color_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ColorCategory', verbose_name='カラー分類')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
                'db_table': 'items',
                'ordering': ['series__name', 'capacity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemFeeCoef',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_coef', models.IntegerField(verbose_name='料金係数')),
                ('starting_point', models.SmallIntegerField(verbose_name='起点日数')),
                ('end_point', models.SmallIntegerField(blank=True, null=True, verbose_name='終点日数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_fee_coef_set', to='main.Item', verbose_name='アイテム')),
            ],
            options={
                'verbose_name': 'アイテム料金係数',
                'verbose_name_plural': 'アイテム料金係数',
                'db_table': 'item_fee_coefs',
                'ordering': ['item__bland__name', 'item__capacity', 'item__name', 'starting_point'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=main.models.ItemImage._get_image_path, verbose_name='画像')),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image_set', to='main.Item', verbose_name='アイテム')),
            ],
            options={
                'verbose_name': 'アイテム画像',
                'verbose_name_plural': 'アイテム画像',
                'db_table': 'item_images',
                'ordering': ['item__bland__name', 'item__capacity', 'item__name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('name', models.CharField(max_length=50, verbose_name='都道府県名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('is_supported', models.BooleanField(default=True, verbose_name='対応中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'db_table': 'prefectures',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('text', models.TextField(verbose_name='質問')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'db_table': 'questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(verbose_name='表示順')),
                ('name', models.CharField(max_length=50, verbose_name='地域名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('postage', models.IntegerField(default=0, verbose_name='追加送料')),
                ('is_supported', models.BooleanField(default=True, verbose_name='対応中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'db_table': 'regions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='返却日')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('address_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='氏名')),
                ('item_fee', models.IntegerField(blank=True, null=True, verbose_name='小計価格')),
                ('postage', models.IntegerField(blank=True, null=True, verbose_name='送料')),
                ('total_fee', models.IntegerField(blank=True, null=True, verbose_name='合計価格')),
                ('status', models.SmallIntegerField(default=1, verbose_name='ステータス')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Item', verbose_name='アイテム')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='シリーズ名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('bland', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Bland', verbose_name='ブランド')),
            ],
            options={
                'verbose_name': 'シリーズ',
                'verbose_name_plural': 'シリーズ',
                'db_table': 'serieses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='サイズ名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('min_days', models.SmallIntegerField(verbose_name='最小日数')),
                ('max_days', models.SmallIntegerField(blank=True, null=True, verbose_name='最大日数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'サイズ',
                'verbose_name_plural': 'サイズ',
                'db_table': 'sizes',
                'ordering': ['min_days'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='タイプ名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
                ('image', models.ImageField(upload_to=main.models.Type._get_image_path, verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タイプ',
                'verbose_name_plural': 'タイプ',
                'db_table': 'types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Size', verbose_name='サイズ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Type', verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Region', verbose_name='地域'),
        ),
        migrations.AddField(
            model_name='item',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Series', verbose_name='シリーズ'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Size', verbose_name='サイズ'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Type', verbose_name='タイプ'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Question', verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='answer',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Reservation', verbose_name='予約'),
        ),
    ]
