# Generated by Django 2.0.6 on 2018-08-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='reservation',
        ),
    ]
