# Generated by Django 2.0.6 on 2018-08-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_cart_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Cart', verbose_name='カート'),
        ),
    ]
