# Generated by Django 2.0.6 on 2018-08-04 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address_name_kana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='フリガナ'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='age_range',
            field=models.CharField(blank=True, choices=[('teens', '～10代'), ('twenties', '20代'), ('thirties', '30代'), ('forties', '40代'), ('fifties', '50代'), ('sixties', '60代～')], max_length=50, null=True, verbose_name='年齢層'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=50, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prefecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Prefecture', verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='番地・建物名'),
        ),
    ]
